services:
  - type: web
    name: mbm
    runtime: node
    buildCommand: npm install && npx expo export --platform web
    startCommand: node server.mjs
    envVars:
      - key: NODE_VERSION
        value: 24
      - key: TESLA_PUBLIC_KEY_PATH
        value: ./public/.well-known/appspecific/com.tesla.3p.public-key.pem
      - key: TESLA_APP_DOMAIN
        sync: false
      - key: TESLA_CLIENT_ID
        sync: false
      - key: TESLA_CLIENT_SECRET
        sync: false