import { StyleSheet } from "react-native";
import { colors } from "./theme";

export const styles = StyleSheet.create({
  loadingScreen: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: colors.paper },
  safeArea: { flex: 1, backgroundColor: colors.paper },
  dashboardScroll: { flex: 1 },
  scrollContent: { paddingBottom: 68 },
  scrollContentGrow: { flexGrow: 1 },
  container: { width: "100%", maxWidth: 1120, alignSelf: "center", paddingHorizontal: 20 },
  containerMobile: { paddingHorizontal: 12 },
  header: { minHeight: 96, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  brand: { fontFamily: "DMSans_700Bold", fontSize: 18, color: colors.ink, letterSpacing: 0 },
  date: { fontFamily: "DMSans_400Regular", fontSize: 13, color: colors.muted, marginTop: 3, textTransform: "capitalize" },
  iconButton: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, borderColor: colors.line, alignItems: "center", justifyContent: "center", backgroundColor: colors.white },
  supplierPickerButton: { minHeight: 58, flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 14, borderRadius: 8, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, marginBottom: 20 },
  supplierPickerCopy: { flex: 1 },
  supplierPickerLabel: { fontFamily: "DMSans_700Bold", fontSize: 9, color: colors.muted },
  supplierPickerName: { fontFamily: "DMSans_700Bold", fontSize: 14, color: colors.ink, marginTop: 3 },
  supplierPickerArea: { fontFamily: "DMSans_700Bold", fontSize: 11, color: colors.green, backgroundColor: colors.mint, paddingVertical: 5, paddingHorizontal: 8, borderRadius: 5 },
  dashboardContext: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 2, marginBottom: 14 },
  dashboardContextLabel: { fontFamily: "DMSans_700Bold", fontSize: 9, color: colors.muted },
  dashboardContextValue: { fontFamily: "DMSans_700Bold", fontSize: 11, color: colors.green },
  addressSectionLabel: { fontFamily: "DMSans_700Bold", fontSize: 9, letterSpacing: 0.2, color: colors.muted, marginTop: 16, marginBottom: 7 },
  addressSearchWrap: { minHeight: 58, flexDirection: "row", alignItems: "center", gap: 10, padding: 8, borderRadius: 8, backgroundColor: colors.white, borderWidth: 1, borderColor: "#C9D5C7", marginTop: 0 },
  addressIconWrap: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 6, backgroundColor: colors.mint },
  addressInputCopy: { flex: 1, minWidth: 0 },
  addressInput: { minWidth: 0, paddingVertical: 7, fontFamily: "DMSans_400Regular", fontSize: 13, color: colors.ink },
  addressSuggestions: { backgroundColor: colors.white, borderRadius: 7, borderWidth: 1, borderColor: colors.line, marginTop: 8, marginBottom: 12, overflow: "hidden" },
  addressSuggestion: { minHeight: 42, justifyContent: "center", paddingHorizontal: 12, borderBottomWidth: 1, borderBottomColor: colors.line },
  addressSuggestionText: { fontFamily: "DMSans_500Medium", fontSize: 12, color: colors.ink },
  addressError: { fontFamily: "DMSans_400Regular", fontSize: 10, lineHeight: 15, color: "#A4462E", marginTop: 6, marginHorizontal: 2 },
  notice: { flexDirection: "row", alignItems: "center", gap: 8, paddingVertical: 10, paddingHorizontal: 12, backgroundColor: "#F8E1D8", borderRadius: 6, marginBottom: 16 },
  noticeText: { fontFamily: "DMSans_500Medium", fontSize: 13, color: "#8A492F" },
  modalBackdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(24,51,47,0.28)" },
  supplierModal: { maxHeight: "82%", backgroundColor: colors.paper, borderTopLeftRadius: 14, borderTopRightRadius: 14, padding: 20 },
  modalHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  modalClose: { width: 36, height: 36, alignItems: "center", justifyContent: "center", borderRadius: 18, backgroundColor: colors.white },
  modalHint: { fontFamily: "DMSans_400Regular", fontSize: 12, color: colors.muted, marginTop: 8, marginBottom: 12 },
  manualChoiceHeading: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 7 },
  manualChoiceLine: { flex: 1, height: 1, backgroundColor: colors.line },
  supplierList: { flexGrow: 0, marginTop: 8 },
  supplierOption: { minHeight: 54, flexDirection: "row", alignItems: "center", paddingHorizontal: 12, borderRadius: 7, backgroundColor: colors.white, marginBottom: 7, borderWidth: 1, borderColor: "#E3E3D9" },
  supplierOptionActive: { borderColor: colors.green, backgroundColor: "#EDF3E9" },
  supplierOptionCopy: { flex: 1 },
  supplierOptionName: { fontFamily: "DMSans_700Bold", fontSize: 12, color: colors.ink },
  supplierOptionArea: { fontFamily: "DMSans_400Regular", fontSize: 10, color: colors.muted, marginTop: 3 },
  utilityPanel: { backgroundColor: colors.white, borderRadius: 8, padding: 18, borderWidth: 1, borderColor: "#E8E6DC", marginTop: 8, marginBottom: 28 },
  utilityGrid: { flexDirection: "row", gap: 8, marginTop: 16 },
  utilityValue: { flex: 1, backgroundColor: "#F1F3ED", borderRadius: 6, padding: 10 },
  utilityLabel: { fontFamily: "DMSans_700Bold", fontSize: 9, color: colors.muted },
  utilityNumber: { fontFamily: "Fraunces_600SemiBold", fontSize: 25, color: colors.ink, marginTop: 5 },
  utilityUnit: { fontFamily: "DMSans_400Regular", fontSize: 10, color: colors.muted, marginTop: 1 },
  utilityMeta: { fontFamily: "DMSans_400Regular", fontSize: 10, color: colors.muted, marginTop: 12, textTransform: "capitalize" },
  loginPanel: { backgroundColor: "#E7EEE4", borderRadius: 8, padding: 18, marginTop: 8, marginBottom: 28 },
  loginHeadingCopy: { flex: 1 },
  loginText: { fontFamily: "DMSans_400Regular", fontSize: 12, lineHeight: 18, color: colors.muted, marginTop: 12, marginBottom: 12 },
  loginInput: { minHeight: 42, borderRadius: 6, borderWidth: 1, borderColor: "#C9D5C7", backgroundColor: colors.white, paddingHorizontal: 12, marginTop: 7, fontFamily: "DMSans_400Regular", fontSize: 13, color: colors.ink },
  loginError: { fontFamily: "DMSans_500Medium", fontSize: 11, lineHeight: 16, color: "#A4462E", marginTop: 9 },
  loginButton: { minHeight: 42, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, borderRadius: 6, backgroundColor: colors.green, marginTop: 12, paddingHorizontal: 14 },
  loginButtonDisabled: { opacity: 0.65 },
  loginButtonText: { fontFamily: "DMSans_700Bold", fontSize: 12, color: colors.white },
  loginPrivacy: { fontFamily: "DMSans_400Regular", fontSize: 10, lineHeight: 15, color: colors.muted, textAlign: "center", marginTop: 10 },
  topGrid: { gap: 14 },
  topGridTablet: { flexDirection: "row" },
  halfPanel: { flex: 1 },
  hero: { minHeight: 315, borderRadius: 8, padding: 24, justifyContent: "space-between", overflow: "hidden" },
  heroMobile: { minHeight: 270, padding: 18 },
  heroTopline: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  eyebrow: { fontFamily: "DMSans_700Bold", fontSize: 11, color: colors.muted, letterSpacing: 0 },
  priceLine: { flexDirection: "row", alignItems: "flex-end", gap: 10, marginVertical: 12 },
  price: { fontFamily: "Fraunces_600SemiBold", fontSize: 94, lineHeight: 102, color: colors.ink, maxWidth: "74%" },
  unitWrap: { paddingBottom: 14 },
  unit: { fontFamily: "DMSans_700Bold", color: colors.ink, fontSize: 22 },
  unitSmall: { fontFamily: "DMSans_400Regular", color: colors.muted, fontSize: 12 },
  statusPill: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 7, borderRadius: 18, paddingVertical: 7, paddingHorizontal: 11 },
  statusDot: { width: 7, height: 7, borderRadius: 4 },
  statusText: { fontFamily: "DMSans_700Bold", fontSize: 12 },
  vatNote: { fontFamily: "DMSans_400Regular", fontSize: 12, color: colors.muted, marginTop: 9 },
  trendPanel: { minHeight: 315, backgroundColor: colors.white, borderRadius: 8, padding: 22, borderWidth: 1, borderColor: "#E8E6DC" },
  trendPanelMobile: { minHeight: 315, padding: 15 },
  sectionHeadingRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  sectionTitle: { fontFamily: "Fraunces_600SemiBold", fontSize: 24, color: colors.ink, marginTop: 4 },
  chartWrap: { flex: 1, justifyContent: "flex-end", marginTop: 8 },
  dayNavigator: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", minHeight: 48, borderBottomWidth: 1, borderBottomColor: colors.line, marginBottom: 8 },
  dayNavigatorTitle: { alignItems: "center" },
  dayNavigatorDate: { fontFamily: "DMSans_700Bold", color: colors.ink, fontSize: 14, textTransform: "capitalize" },
  dayNavigatorMeta: { fontFamily: "DMSans_400Regular", color: colors.muted, fontSize: 10, marginTop: 2 },
  dayArrow: { width: 36, height: 36, alignItems: "center", justifyContent: "center" },
  dayArrowDisabled: { opacity: 0.25 },
  chartSelection: { minHeight: 58, justifyContent: "flex-end" },
  chartSelectionHeader: { flexDirection: "row", alignItems: "center", gap: 8 },
  chartSelectionTime: { fontFamily: "DMSans_700Bold", color: colors.ink, fontSize: 13 },
  scrubBadge: { backgroundColor: colors.mint, paddingHorizontal: 7, paddingVertical: 2, borderRadius: 4 },
  scrubBadgeText: { fontFamily: "DMSans_700Bold", fontSize: 9, color: colors.green, textTransform: "uppercase" },
  chartSelectionValue: { flexDirection: "row", alignItems: "baseline", gap: 6 },
  chartSelectionPrice: { fontFamily: "Fraunces_600SemiBold", color: colors.ink, fontSize: 38, lineHeight: 43 },
  chartSelectionUnit: { fontFamily: "DMSans_500Medium", color: colors.muted, fontSize: 13 },
  barViewport: { height: 156, overflow: "hidden", position: "relative" },
  barChart: { height: 156, flexDirection: "row", alignItems: "flex-end", gap: 4, paddingTop: 14, paddingBottom: 6, paddingHorizontal: 16 },
  barChartOverview: { minWidth: "100%", gap: 1, paddingHorizontal: 4 },
  barSlot: { width: 27, height: "100%", justifyContent: "flex-end", alignItems: "center", position: "relative" },
  barSlotOverview: { width: "auto", flex: 1 },
  barSlotSelected: { backgroundColor: "rgba(22, 59, 71, 0.08)", borderRadius: 4 },
  bar: { width: 27, minHeight: 30, borderTopLeftRadius: 4, borderTopRightRadius: 4 },
  barOverview: { width: "100%", borderTopLeftRadius: 2, borderTopRightRadius: 2 },
  barHour: { height: 18, paddingTop: 4, fontFamily: "DMSans_400Regular", fontSize: 9, color: colors.muted },
  barHourOverview: { fontSize: 8 },
  barHourCurrent: { fontFamily: "DMSans_700Bold", color: colors.ink },
  currentBar: { borderWidth: 2, borderColor: colors.ink },
  cheapestBar: { borderWidth: 2, borderColor: colors.green },
  selectedBar: { borderWidth: 2, borderColor: colors.navy },
  currentMarker: { position: "absolute", backgroundColor: colors.ink, borderRadius: 8, paddingHorizontal: 5, paddingVertical: 2, zIndex: 2 },
  cheapestMarker: { backgroundColor: colors.green },
  scrubMarker: { backgroundColor: colors.navy },
  currentMarkerText: { fontFamily: "DMSans_700Bold", fontSize: 8, color: colors.white },
  railFadeLeft: { position: "absolute", left: 0, top: 0, bottom: 0, width: 16, pointerEvents: "none" },
  railFadeRight: { position: "absolute", right: 0, top: 0, bottom: 0, width: 16, pointerEvents: "none" },
  sliderWrapper: { marginHorizontal: 10, marginTop: 2, marginBottom: 4 },
  sliderTouchArea: { height: 22, justifyContent: "center", position: "relative" },
  sliderDot: { position: "absolute", top: 6, width: 10, height: 10, borderRadius: 5, backgroundColor: colors.green },
  sliderDotActive: { backgroundColor: colors.ink, transform: [{ scale: 1.3 }] },
  swipeHint: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5, borderTopWidth: 1, borderTopColor: colors.line, paddingTop: 7 },
  chartToolbar: { minHeight: 38, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderTopWidth: 1, borderTopColor: colors.line, paddingTop: 7 },
  overviewButton: { minHeight: 30, flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 10, borderRadius: 5, backgroundColor: "#ECEFE5" },
  overviewButtonText: { fontFamily: "DMSans_700Bold", fontSize: 10, color: colors.ink },
  chartLabel: { fontFamily: "DMSans_400Regular", color: colors.muted, fontSize: 10 },
  chartLabelActive: { color: colors.green, fontFamily: "DMSans_700Bold" },
  teslaCard: { marginTop: 18, padding: 15, borderRadius: 8, backgroundColor: "#E8F0EC", borderWidth: 1, borderColor: "#C7D9CD" },
  teslaCardHeader: { flexDirection: "row", alignItems: "center", gap: 11 },
  teslaIcon: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center", backgroundColor: colors.white },
  teslaCardCopy: { flex: 1 },
  teslaCardActions: { alignItems: "center", gap: 8 },
  teslaVisibilityButton: { width: 30, height: 30, alignItems: "center", justifyContent: "center", borderRadius: 15, backgroundColor: "rgba(255,254,250,0.7)" },
  teslaVisibilityButtonActive: { backgroundColor: colors.white },
  teslaCardTitle: { fontFamily: "DMSans_700Bold", fontSize: 14, color: colors.ink },
  teslaCardText: { fontFamily: "DMSans_400Regular", fontSize: 11, lineHeight: 16, color: colors.muted, marginTop: 3 },
  teslaStatusDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: "#B6C0BA" },
  teslaStatusDotConnected: { backgroundColor: colors.green },
  teslaStats: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 15, paddingTop: 13, borderTopWidth: 1, borderTopColor: "#C7D9CD" },
  teslaPrimaryStat: { minWidth: 92, flex: 1, paddingRight: 8 },
  teslaStat: { minWidth: 92, flex: 1, paddingRight: 8 },
  teslaBatteryNumber: { fontFamily: "Fraunces_600SemiBold", fontSize: 28, color: colors.ink },
  teslaStatValue: { minHeight: 34, fontFamily: "DMSans_700Bold", fontSize: 13, color: colors.ink },
  teslaStatLabel: { fontFamily: "DMSans_700Bold", fontSize: 8, color: colors.muted, marginTop: 3 },
  teslaConnectButton: { minHeight: 36, marginTop: 13, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, borderRadius: 18, backgroundColor: colors.ink },
  teslaConnectButtonText: { fontFamily: "DMSans_700Bold", fontSize: 11, color: colors.white },
  plannerSection: { marginVertical: 26 },
  plannerHeading: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 14 },
  addDeviceButton: { minHeight: 38, flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 13, borderRadius: 19, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.white },
  addDeviceButtonActive: { backgroundColor: colors.ink, borderColor: colors.ink },
  addDeviceText: { fontFamily: "DMSans_700Bold", fontSize: 11, color: colors.ink },
  addDeviceTextActive: { color: colors.white },
  deviceCatalog: { backgroundColor: "#E7EEE4", borderRadius: 8, padding: 14, marginBottom: 12 },
  catalogLabel: { fontFamily: "DMSans_700Bold", fontSize: 10, color: colors.muted, marginBottom: 10 },
  catalogGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  catalogItem: { flexGrow: 1, flexBasis: "45%", minHeight: 62, flexDirection: "row", alignItems: "center", gap: 8, padding: 9, borderRadius: 6, backgroundColor: colors.white, borderWidth: 1, borderColor: "#D7DFD4" },
  catalogIcon: { width: 32, height: 32, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: colors.mint },
  catalogName: { flex: 1, fontFamily: "DMSans_700Bold", fontSize: 11, color: colors.ink },
  plannerEmpty: { minHeight: 220, alignItems: "center", justifyContent: "center", padding: 28, borderRadius: 8, borderWidth: 1, borderStyle: "dashed", borderColor: "#BFC9BC", backgroundColor: "rgba(255,254,250,0.55)" },
  emptyIcon: { width: 50, height: 50, borderRadius: 25, alignItems: "center", justifyContent: "center", backgroundColor: colors.mint, marginBottom: 13 },
  emptyTitle: { fontFamily: "Fraunces_600SemiBold", fontSize: 21, color: colors.ink, textAlign: "center" },
  emptyText: { maxWidth: 310, fontFamily: "DMSans_400Regular", fontSize: 12, lineHeight: 18, color: colors.muted, textAlign: "center", marginTop: 7 },
  emptyAction: { minHeight: 36, flexDirection: "row", alignItems: "center", gap: 6, borderRadius: 18, paddingHorizontal: 14, backgroundColor: colors.green, marginTop: 17 },
  emptyActionText: { fontFamily: "DMSans_700Bold", fontSize: 11, color: colors.white },
  deviceList: { gap: 10 },
  deviceCard: { backgroundColor: colors.white, borderRadius: 8, padding: 15, borderWidth: 1, borderColor: "#E3E3D9" },
  deviceHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  deviceIdentity: { flex: 1, flexDirection: "row", alignItems: "center", gap: 10 },
  deviceIcon: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center", backgroundColor: colors.mint },
  deviceName: { fontFamily: "DMSans_700Bold", fontSize: 15, color: colors.ink },
  deviceMeta: { fontFamily: "DMSans_400Regular", fontSize: 10, color: colors.muted, marginTop: 2 },
  deviceActions: { flexDirection: "row", gap: 5 },
  deviceActionButton: { width: 34, height: 34, alignItems: "center", justifyContent: "center", borderRadius: 17, backgroundColor: "#F1F1EB" },
  deviceActionButtonActive: { backgroundColor: colors.mint },
  devicePlan: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", gap: 10, borderTopWidth: 1, borderTopColor: colors.line, marginTop: 13, paddingTop: 13 },
  devicePlanLabel: { fontFamily: "DMSans_700Bold", fontSize: 9, color: colors.green },
  devicePlanTime: { fontFamily: "DMSans_700Bold", fontSize: 13, color: colors.ink, marginTop: 4, textTransform: "capitalize" },
  devicePriceWrap: { alignItems: "flex-end" },
  devicePrice: { fontFamily: "Fraunces_600SemiBold", fontSize: 24, color: colors.ink },
  deviceSaving: { fontFamily: "DMSans_500Medium", fontSize: 9, color: colors.green, marginTop: 1 },
  cheapestSuggestion: { minHeight: 38, flexDirection: "row", alignItems: "center", gap: 7, borderRadius: 6, backgroundColor: "#EDF3E9", paddingHorizontal: 10, marginTop: 10 },
  cheapestSuggestionText: { flex: 1, fontFamily: "DMSans_500Medium", fontSize: 10, color: colors.ink, textTransform: "capitalize" },
  cheapestSaving: { fontFamily: "DMSans_700Bold", fontSize: 10, color: colors.green },
  deviceSettings: { borderTopWidth: 1, borderTopColor: colors.line, marginTop: 14, paddingTop: 14 },
  simpleSettingGroup: { marginBottom: 13 },
  simpleSettingTitle: { fontFamily: "DMSans_700Bold", fontSize: 11, color: colors.ink, marginBottom: 8 },
  choiceGrid: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  classChoice: { width: "22%", minHeight: 40, alignItems: "center", justifyContent: "center", borderRadius: 5, borderWidth: 1, borderColor: "transparent", opacity: 0.72 },
  classChoiceActive: { borderWidth: 3, borderColor: colors.ink, opacity: 1 },
  classChoiceText: { fontFamily: "DMSans_700Bold", fontSize: 12, color: colors.white },
  classChoiceTextDark: { color: colors.ink },
  estimateCaption: { fontFamily: "DMSans_500Medium", fontSize: 10, color: colors.green, marginTop: 7 },
  durationGrid: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  durationChoice: { width: "23%", minHeight: 35, alignItems: "center", justifyContent: "center", borderRadius: 5, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.white },
  durationChoiceActive: { backgroundColor: colors.ink, borderColor: colors.ink },
  durationChoiceText: { fontFamily: "DMSans_500Medium", fontSize: 10, color: colors.muted },
  durationChoiceTextActive: { fontFamily: "DMSans_700Bold", color: colors.white },
  controlRow: { flexDirection: "row", gap: 8, marginBottom: 8 },
  vehicleLookupGroup: { marginBottom: 14 },
  vehicleLookupRow: { flexDirection: "row", gap: 8 },
  vehiclePlateInput: { flex: 1, minWidth: 0, minHeight: 38, borderRadius: 6, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.white, paddingHorizontal: 10, fontFamily: "DMSans_700Bold", fontSize: 13, color: colors.ink },
  vehicleModelSuggestions: { marginTop: 6, borderRadius: 6, overflow: "hidden", borderWidth: 1, borderColor: colors.line },
  vehicleModelOption: { minHeight: 36, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 10, backgroundColor: colors.white, borderBottomWidth: 1, borderBottomColor: colors.line },
  vehicleModelOptionName: { fontFamily: "DMSans_500Medium", fontSize: 11, color: colors.ink },
  vehicleModelOptionBattery: { fontFamily: "DMSans_700Bold", fontSize: 10, color: colors.green },
  vehicleLookupHint: { fontFamily: "DMSans_400Regular", fontSize: 10, lineHeight: 15, color: colors.muted, marginTop: 6 },
  labelConversion: { fontFamily: "DMSans_700Bold", fontSize: 10, color: colors.green, marginTop: 3 },
  deviceHelp: { fontFamily: "DMSans_400Regular", fontSize: 10, lineHeight: 15, color: colors.muted, marginTop: 4 },
  stepper: { flex: 1, backgroundColor: "#F1F3ED", borderRadius: 6, padding: 9 },
  stepperLabel: { fontFamily: "DMSans_500Medium", fontSize: 9, color: colors.muted, marginBottom: 7 },
  stepperControls: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  stepperButton: { width: 28, height: 28, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line },
  stepperValue: { fontFamily: "DMSans_700Bold", fontSize: 13, color: colors.ink },
  numericField: { flex: 1, backgroundColor: "#F1F3ED", borderRadius: 6, padding: 9 },
  numericInputWrap: { minHeight: 30, flexDirection: "row", alignItems: "center", borderRadius: 5, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.white, paddingHorizontal: 9 },
  numericInput: { flex: 1, minWidth: 0, paddingVertical: 5, fontFamily: "DMSans_700Bold", fontSize: 14, color: colors.ink },
  numericSuffix: { fontFamily: "DMSans_500Medium", fontSize: 9, color: colors.muted },
  smallMeta: { fontFamily: "DMSans_400Regular", fontSize: 12, color: colors.muted },
  hourGrid: { marginTop: 12, borderTopWidth: 1, borderTopColor: colors.line },
  hourGridTablet: { flexDirection: "row", flexWrap: "wrap" },
  hourRow: { minHeight: 68, flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderBottomColor: colors.line, paddingHorizontal: 8 },
  hourRowTablet: { flexBasis: "50%", flexGrow: 0, flexShrink: 0 },
  hourRowCurrent: { backgroundColor: "#ECEFE5" },
  hourTimeWrap: { flex: 1 },
  hourTime: { fontFamily: "DMSans_700Bold", fontSize: 16, color: colors.ink },
  hourRelative: { fontFamily: "DMSans_400Regular", fontSize: 10, color: colors.muted, marginTop: 2 },
  hourPriceWrap: { flexDirection: "row", alignItems: "baseline", gap: 4 },
  hourPrice: { fontFamily: "Fraunces_600SemiBold", fontSize: 25, color: colors.ink },
  hourUnit: { fontFamily: "DMSans_400Regular", fontSize: 11, color: colors.muted },
  miniDot: { width: 8, height: 8, borderRadius: 4, marginLeft: 14 },
  daysHeading: { marginTop: 34 },
  dayGrid: { marginTop: 13, gap: 10 },
  dayGridTablet: { flexDirection: "row" },
  dayItem: { flex: 1, minHeight: 132, paddingVertical: 18, borderTopWidth: 3, borderTopColor: colors.coral, borderBottomWidth: 1, borderBottomColor: colors.line },
  dayName: { fontFamily: "DMSans_700Bold", fontSize: 13, color: colors.muted, textTransform: "capitalize" },
  dayPrice: { fontFamily: "Fraunces_600SemiBold", fontSize: 31, color: colors.ink, marginTop: 10 },
  dayUnit: { fontFamily: "DMSans_400Regular", fontSize: 12, color: colors.muted },
  rangeLine: { flexDirection: "row", justifyContent: "space-between", marginTop: 8 },
  rangeText: { fontFamily: "DMSans_400Regular", fontSize: 11, color: colors.muted },
  disclosure: { flexDirection: "row", alignItems: "flex-start", gap: 10, marginTop: 28, paddingTop: 18, borderTopWidth: 1, borderTopColor: colors.line },
  disclosureText: { flex: 1, fontFamily: "DMSans_400Regular", fontSize: 12, lineHeight: 18, color: colors.muted },
  bottomNavigation: { flexDirection: "row", gap: 6, padding: 5, marginBottom: 20, borderRadius: 8, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line },
  navigationItem: { flex: 1, minHeight: 42, alignItems: "center", justifyContent: "center", gap: 4, borderRadius: 6 },
  navigationItemActive: { backgroundColor: colors.mint },
  navigationText: { fontFamily: "DMSans_500Medium", fontSize: 10, color: colors.muted },
  navigationTextActive: { fontFamily: "DMSans_700Bold", color: colors.green },
  pageEyebrow: { fontFamily: "DMSans_700Bold", fontSize: 10, color: colors.muted, marginTop: 10 },
  pageTitle: { fontFamily: "Fraunces_600SemiBold", fontSize: 32, lineHeight: 38, color: colors.ink, marginTop: 5 },
  pageIntro: { fontFamily: "DMSans_400Regular", fontSize: 13, lineHeight: 19, color: colors.muted, marginTop: 8, marginBottom: 18 },
  profileCard: { alignItems: "center", padding: 24, marginVertical: 18, borderRadius: 8, backgroundColor: colors.white, borderWidth: 1, borderColor: "#E8E6DC" },
  profileAvatar: { width: 58, height: 58, alignItems: "center", justifyContent: "center", borderRadius: 29, backgroundColor: colors.mint },
  profileName: { fontFamily: "Fraunces_600SemiBold", fontSize: 23, color: colors.ink, marginTop: 12 },
  profileEmail: { fontFamily: "DMSans_400Regular", fontSize: 13, color: colors.muted, marginTop: 3 },
  profileInput: { width: "100%", minHeight: 44, marginTop: 8, paddingHorizontal: 12, borderRadius: 6, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.paper, fontFamily: "DMSans_400Regular", fontSize: 13, color: colors.ink },
  profileSaveButton: { minHeight: 38, minWidth: 120, alignItems: "center", justifyContent: "center", marginTop: 12, paddingHorizontal: 18, borderRadius: 6, backgroundColor: colors.green },
  profileSaveText: { fontFamily: "DMSans_700Bold", fontSize: 11, color: colors.white },
  profileAddressCard: { padding: 14, marginTop: 10, borderRadius: 8, backgroundColor: "#E7EEE4" },
  currentSupplierRow: { paddingTop: 14, marginTop: 12, borderTopWidth: 1, borderTopColor: "#C9D5C7" },
  currentSupplierLabel: { fontFamily: "DMSans_700Bold", fontSize: 9, color: colors.muted },
  currentSupplierName: { fontFamily: "DMSans_700Bold", fontSize: 14, color: colors.ink, marginTop: 4 },
  dashboardDevicesSummary: { padding: 18, marginTop: 22, marginBottom: 28, borderRadius: 8, backgroundColor: colors.white, borderWidth: 1, borderColor: "#E8E6DC" },
  dashboardSummaryText: { fontFamily: "DMSans_400Regular", fontSize: 13, color: colors.muted, marginTop: 5 },
  quickDeviceList: { gap: 7, marginTop: 14 },
  quickDeviceItem: { minHeight: 52, flexDirection: "row", alignItems: "center", gap: 9, paddingHorizontal: 9, borderRadius: 6, backgroundColor: "#F1F3ED" },
  quickDeviceIcon: { width: 30, height: 30, alignItems: "center", justifyContent: "center", borderRadius: 15, backgroundColor: colors.mint },
  quickDeviceCopy: { flex: 1 },
  quickDeviceName: { fontFamily: "DMSans_700Bold", fontSize: 12, color: colors.ink },
  quickDeviceMeta: { fontFamily: "DMSans_400Regular", fontSize: 10, color: colors.muted, marginTop: 2 },
  dashboardSummaryButton: { minHeight: 38, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, marginTop: 14, borderRadius: 6, backgroundColor: colors.green },
  dashboardSummaryButtonText: { fontFamily: "DMSans_700Bold", fontSize: 11, color: colors.white },
  wastePanel: { padding: 18, marginBottom: 28, borderRadius: 8, backgroundColor: "#E7EEE4" },
  wasteEvent: { minHeight: 58, flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 9, borderTopWidth: 1, borderTopColor: "#C9D5C7" },
  wasteDate: { width: 42, alignItems: "center" },
  wasteDateDay: { fontFamily: "Fraunces_600SemiBold", fontSize: 22, lineHeight: 24, color: colors.ink },
  wasteDateMonth: { fontFamily: "DMSans_700Bold", fontSize: 9, color: colors.green, textTransform: "uppercase" },
  wasteEventCopy: { flex: 1 },
  wasteEventTitle: { fontFamily: "DMSans_700Bold", fontSize: 12, color: colors.ink },
  wasteEventMeta: { fontFamily: "DMSans_400Regular", fontSize: 10, color: colors.muted, marginTop: 2 },
  wasteEmpty: { fontFamily: "DMSans_400Regular", fontSize: 12, lineHeight: 18, color: colors.muted, marginTop: 8 },
  wasteAction: { minHeight: 36, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, marginTop: 12, borderRadius: 6, backgroundColor: colors.green },
  wasteActionText: { fontFamily: "DMSans_700Bold", fontSize: 11, color: colors.white },
});
